CREATE TABLE IF NOT EXISTS IFS_USERS_TBL (
  ID            INT          NOT NULL              AUTO_INCREMENT,
  FIRST_NAME    VARCHAR(255) NOT NULL,
  LAST_NAME     VARCHAR(255) NOT NULL,
  EMAIL_ADDRESS VARCHAR(255),
  CREATED_DATE  TIMESTAMP(6) NOT NULL              DEFAULT CURRENT_TIMESTAMP(6),
  UPDATED_DATE  TIMESTAMP(6) NOT NULL              DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (ID)
);